Branding redesign
woelper/oculante pull request #425
Opened 2024-09-15 21:47 UTC by Stoppedpuma

Redesigns banner and icons. Icons have the three variants @woelper chose. This is being opened as a PR to master instead of the redesign branch to be ready for publishing on flathub.

These assets can be downloaded [here!](https://www.figma.com/design/we5ws6DFbPjbLMKKnhOpIb/oculante-Branding-Update-2024-09-16?node-id=0-1&t=xbVxU4bGCzEhFkA4-1)

2024-09-16 20:30 UTC, Stoppedpuma commented
@woelper This should be ready to merge if you're finished with your review!

2024-09-17 09:48 UTC, woelper requested changes
Could you please revert the avif icons back to png? The format may be better, but I like to keep things simple. I also suspect copying into a file with png extension will work, as in the `pkgbuild`.

2024-09-17 09:48 UTC, woelper commented on PKGBUILD
> +	install -Dm644 res/icons/icon.avif "${pkgdir}/usr/share/icons/hicolor/128x128/apps/${pkgname}.png"
Do I understand correctly that the avif is just copied into a png? If so, this might not work. I'd vote for keeping the image format as png in order not to introduce any issues.

2024-09-17 10:22 UTC, Stoppedpuma commented on PKGBUILD
> +	install -Dm644 res/icons/icon.avif "${pkgdir}/usr/share/icons/hicolor/128x128/apps/${pkgname}.png"
The icons are now png again

2024-09-17 18:39 UTC, woelper requested changes

2024-09-17 18:39 UTC, woelper commented on PKGBUILD
> +	install -Dm644 res/icons/icon.avif "${pkgdir}/usr/share/icons/hicolor/128x128/apps/${pkgname}.png"
This needs to be changed to png please since the avif is no longer present

2024-09-17 20:54 UTC, woelper approved these changes

2024-09-17 20:54 UTC, merged